import { OperationError } from '@tezblock/domain/operations';

export interface Transaction {
  secret?: any; // TODO: any (loads of)
  storage_size?: any;
  delegatable?: any;
  source?: string;
  consumed_gas?: number;
  timestamp: number;
  pkh?: any;
  nonce?: any;
  block_level: number;
  balance?: number;
  branch?: string;
  operation_group_hash: string;
  public_key?: any;
  paid_storage_size_diff?: any;
  amount: number;
  delegate: string;
  block_hash: string;
  spendable?: boolean;
  status?: string;
  operation_id: number;
  manager_pubkey?: any;
  slots: string;
  storage_limit?: any;
  storage?: any;
  counter?: any;
  script?: any;
  kind: string;
  gas_limit?: any;
  parameters?: any;
  parameters_micheline?: any;
  parameters_entrypoints?: any;
  destination?: any;
  fee: number;
  level: number;
  delegatedBalance?: number;
  originatedBalance?: number;
  proposal?: string;
  cycle?: number;
  stakingBalance: string;
  bakingRewards: string;
  endorsingRewards: string;
  fees: string;
  totalRewards: string;
  originated_contracts?: string;
  payouts?: any;
  // These are our own properties
  votes?: number;
  voting_period?: string;
  burn?: string;
  symbol?: string;
  baker?: string;
  errors?: OperationError[];
  outgoing?: boolean;
  reward?: string;
  offender?: string;
  lostAmount?: string;
  denouncedLevel?: number;
}
