apiVersion: v1
kind: Service
metadata:
  name: tezblock-delphinet-frontend
  namespace: tezblock
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: tezblock-delphinet-frontend
