apiVersion: apps/v1
kind: Deployment
metadata:
  name: tezblock-ithacanet-frontend
  namespace: tezblock
  labels:
    app: tezblock-ithacanet-frontend
spec:
  selector:
    matchLabels:
      app: tezblock-ithacanet-frontend
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: tezblock-ithacanet-frontend
    spec:
      containers:
        - name: tezblock-ithacanet-frontend
          image: _TO_BE_REPLACED_BY_IMAGE_TAG_
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: tezblock-ithacanet-frontend-config-map
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 5
      imagePullSecrets:
        - name: regsecret
      restartPolicy: Always
status: {}
