import { EMPTY } from 'rxjs';

export const getApiServiceMock = () =>
  jasmine.createSpyObj('ApiService', {
    getCurrentCycleRange: EMPTY,
    getLatestTransactions: EMPTY,
    getTransactionsById: EMPTY,
    addVoteData: EMPTY,
    getEndorsementsById: EMPTY,
    getTransactionsByBlock: EMPTY,
    getTransactionsByField: EMPTY,
    getTransactionsByPredicates: EMPTY,
    getAccountById: EMPTY,
    getAccountsByIds: EMPTY,
    getAccountsStartingWith: EMPTY,
    getTransactionHashesStartingWith: EMPTY,
    getBlockHashesStartingWith: EMPTY,
    getDelegatedAccounts: EMPTY,
    getLatestBlocks: EMPTY,
    getLatestBlocksWithData: EMPTY,
    getAdditionalBlockField: Promise.resolve(),
    getAdditionalBlockFieldObservable: EMPTY,
    getBlockById: EMPTY,
    getBlocksOfIds: EMPTY,
    getBlockByHash: EMPTY,
    getVotesForTransaction: EMPTY,
    getAggregatedBakingRights: EMPTY,
    getBakingRightsItems: EMPTY,
    getAggregatedEndorsingRights: EMPTY,
    getEndorsingRightItems: EMPTY,
    getVotingPeriod: EMPTY,
    getActiveBakers: EMPTY,
    getTotalBakersAtTheLatestBlock: EMPTY,
    getNumberOfDelegatorsByBakers: EMPTY,
    getProposal: EMPTY,
    getProposals: EMPTY,
    getTransferOperationsForContract: EMPTY,
    getBalanceForLast30Days: EMPTY,
    getEarlierBalance: EMPTY,
    getErrorsForOperations: EMPTY,
    getOperationCount: EMPTY,
    getEndorsedSlotsCount: EMPTY,
    getFrozenBalance: Promise.resolve(),
    getDelegatedAccountsList: EMPTY,
  });
