import { of } from 'rxjs'

export const getApiServiceMock = () => jasmine.createSpyObj('ApiService', {
  getCurrentCycleRange: of([]),
  getLatestTransactions: of([]),
  getTransactionsById: of([]),
  addVoteData: of([]),
  getEndorsementsById: of([]),
  getTransactionsByBlock: of([]),
  getTransactionsByField: of([]),
  getTransactionsByPredicates: of([]),
  getLatestAccounts: of([]),
  getAccountById: of([]),
  getAccountsByIds: of([]),
  getAccountsStartingWith: of([]),
  getTransactionHashesStartingWith: of([]),
  getBlockHashesStartingWith: of([]),
  getDelegatedAccounts: of([]),
  getManagerAccount: of([]),
  getLatestBlocks: of([]),
  getLatestBlocksWithData: of([]),
  getAdditionalBlockField: of([]).toPromise(),
  getAdditionalBlockFieldObservable: of([]),
  getBlockById: of([]),
  getBlocksOfIds: of([]),
  getBlockByHash: of([]),
  getVotesForTransaction: of(null),
  getAggregatedBakingRights: of([]),
  getBakingRightsItems: of([]),
  getAggregatedEndorsingRights: of([]),
  getEndorsingRightItems: of([]),
  getVotingPeriod: of([]),
  getActiveBakers: of([]),
  getTotalBakersAtTheLatestBlock: of(null),
  getNumberOfDelegatorsByBakers: of([]),
  getProposal: of(null),
  getProposals: of([]),
  getTransferOperationsForContract: of(null),
  getBalanceForLast30Days: of([]),
  getEarlierBalance: of([]),
  getErrorsForOperations: of([]),
  getOperationCount: of([]),
  getEndorsedSlotsCount: of(null),
  getFrozenBalance: of(null).toPromise(),
  getDelegatedAccountsList: of([])
})
